services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gateway
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready", "-U", "postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

  app:
    image: golang:1.24-alpine
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    working_dir: /app
    command: go run cmd/app/main.go
    environment:
      - DB_HOST=db
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=gateway
      - DB_PORT=5432
      - DB_SSL_MODE=disable
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

volumes:
  postgres_data:
    driver: local
    driver_opts:
      type: none
      device: /home/gilberto/software-development/fullcycle3/imersao-fullcycle-gateway-de-pagamento/db_data
      o: bind
