### Variaveis globais
@baseUrl = http://localhost:8080
@apiKey = {{createAccount.response.body.api_key}}

### Criar uma conta nova
# @name createAccount
POST {{baseUrl}}/accounts
Content-Type: application/json

{
  "name": "Gilberto Silva",
  "email": "gilberto5@gmail.com"
}

### Obter detalhes da conta
GET {{baseUrl}}/accounts
X-API-Key: {{apiKey}}



### Criar uma nova fatura
# @name createInvoice
POST {{baseUrl}}/invoice
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "amount": 100.50,
  "description": "Fatura de teste",
  "payment_type": "credit_card",
  "card_number": "4111111111111111",
  "cvv": "123",
  "expiry_month": 12,
  "expiry_year": 2025,
  "cardholder_name": "Gilberto Silva"
}

### Obter detalhes da fatura
@invoiceId = {{createInvoice.response.body.id}}
GET {{baseUrl}}/invoice/{{invoiceId}}
X-API-Key: {{apiKey}}

### Criar uma fatura com valor maior que $10000 
# @name createInvoiceOverLimit
POST {{baseUrl}}/invoice
Content-Type: application/json
X-API-Key: {{apiKey}}

{
  "amount": 15000.00,
  "description": "Fatura de teste com valor alto",
  "payment_type": "credit_card",
  "card_number": "4111111111111111",
  "cvv": "123",
  "expiry_month": 12,
  "expiry_year": 2025,
  "cardholder_name": "Gilberto Silva"
}

### Obter detalhes da fatura com valor maior que $10000 que deve ter o status "pending"
@invoiceId = {{createInvoiceOverLimit.response.body.id}}
GET {{baseUrl}}/invoice/{{invoiceId}}
X-API-Key: {{apiKey}}

### Obter todas as faturas de uma conta by api_key
GET {{baseUrl}}/invoices
X-API-Key: {{apiKey}}