services:
  nestjs:
    build: .
    ports:
      - 3001:3000
    volumes:
      - .:/home/node/app

  db:
    image: postgres:16-alpine
    ports:
      - '5433:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: mydb
    # volumes:
    #   - postgres_data:/var/lib/postgresql/data
    # healthcheck:
    #   test: ['CMD-SHELL', 'pg_isready', '-U', 'postgres']
    #   interval: 10s
    #   timeout: 5s
    #   retries: 5
    # restart: unless-stopped
